# Generated by Django 3.1.4 on 2020-12-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
