# Generated by Django 3.1.4 on 2020-12-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201213_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
