# Generated by Django 3.1.5 on 2021-01-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('N', 'NEW'), ('C', 'CONFIRMED'), ('F', 'FINISHED'), ('V', 'VOID')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(max_length=128),
        ),
    ]
