# Generated by Django 3.1.5 on 2021-01-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210110_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='not_stated', max_length=256),
        ),
    ]
